#ifndef TESTING_H
#define TESTING_H

#define TESTING_START 0
#define TESTING_UNDEF 2
#define TESTING_ALIGNMENT_FAULT 3
#define TESTING_DATA_READ_FAULT 4
#define TESTING_DATA_WRITE_FAULT 5
#define TESTING_INSTRUCTION_PERMISSION_ABORT 8
#define TESTING_TIMER0 9
#define TESTING_TIMER1 10
#define TESTING_TIMER2 11
#define TESTING_TIMER3 12
#define TESTING_TASK1 14
#define TESTING_TASK2 15
#define TESTING_PRIVILEGED_DATA 16
#define TESTING_PUBLIC_DATA 17
#define TESTING_TABLE_WALK 18

#endif // TESTING_H
